name: nodejs.CI/CD
on: 
  push:
     branches: [ devlop ]
   
jobs:
  build: 
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
       os: [ubuntu-latest]
       node-version: [14.15.1]  
    env:
        CI: true 
    steps: 
      - uses: actions/checkout@v2 
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}  
        uses: actions/setup-node@v1 
        with:        
          node-version: ${{ matrix.node-version }}
      - name: npm ci      
        run: npm ci    
      - name: npm run build
        run: npm run build
